---
name: Check version of VIN database

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  

jobs:
  check-vin:
    runs-on: ubuntu-latest
    name: Checks version of VIN db
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Check VIN
        uses: jazzido/pup-action@v1.0.3
        id: check_vin
        with:
          url: 'https://vpic.nhtsa.dot.gov/api/'
          selector: '.body-content > div:nth-child(6) > p:nth-child(3) text{}'
      # Use the output from the `hello` step
      - name: Output result
        run: echo "${{ steps.check_vin.outputs.result }}" | grep -oP 'updated on ([\d/]+)' | cut -d " " -f 3
